import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyLSfST4aKeJvY3hyx0tFgHBD3fiZvC0Y',
    appId: '1:433544773780:web:a24f322eba628b7e92b481',
    messagingSenderId: '433544773780',
    projectId: 'chatnew-ed05a',
    authDomain: 'chatnew-ed05a.firebaseapp.com',
    storageBucket: 'chatnew-ed05a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2P_fvvZWsgLmj4wgJ7-ZPUPZEtQRWN4A',
    appId: '1:433544773780:android:8618d97191404bc192b481',
    messagingSenderId: '433544773780',
    projectId: 'chatnew-ed05a',
    storageBucket: 'chatnew-ed05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA49MgUxhQ9uvYJmNBNAOFb93trsFFHvJQ',
    appId: '1:433544773780:ios:6fc3023e0012415892b481',
    messagingSenderId: '433544773780',
    projectId: 'chatnew-ed05a',
    storageBucket: 'chatnew-ed05a.appspot.com',
    iosClientId:
        '433544773780-2ko2rr7sf12j0ua4tj51acfdklgr4igr.apps.googleusercontent.com',
    iosBundleId: 'com.example.app07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA49MgUxhQ9uvYJmNBNAOFb93trsFFHvJQ',
    appId: '1:433544773780:ios:238fd801172e3a0d92b481',
    messagingSenderId: '433544773780',
    projectId: 'chatnew-ed05a',
    storageBucket: 'chatnew-ed05a.appspot.com',
    iosClientId:
        '433544773780-eqhclpmsq65b9b8lhr4j97jempm4cg5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.app07.RunnerTests',
  );
}
